apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: go-server
spec:
  template:
    metadata:
        annotations:
          autoscaling.knative.dev/initial-scale: "0"
          # Limit scaling to 2 pods.
          autoscaling.knative.dev/max-scale: "2"
    spec:
      containers:
      - image: haroldo89/go-server:0.0.1
        ports:
        - containerPort: 8090