apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-go
  labels:
    app: go-app
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8090"
    prometheus.io/scrape: "true"
    prometheus.io/scheme: http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8090"
        prometheus.io/scrape: "true"
        prometheus.io/scheme: http
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: localhost:5001/go-server:0.0.1
          ports:
            - containerPort: 8090
              name: http-go-svc
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: sonarqube
        - name: POSTGRES_PASSWORD
          value: sonarqube
        - name: POSTGRES_DB
          value: sonarqube
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 250Mi            
