apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor-deployment-go
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: go-app
  endpoints:
  - port: http-go-svc
    interval: 30s
