apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nginx
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/initial-scale: "0"
    spec:
      containers:
      - image: nginx
        ports:
        - containerPort: 80