apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-go
  labels:
    app: go-app
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8090"
    prometheus.io/scrape: "true"
    prometheus.io/scheme: http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8090"
        prometheus.io/scrape: "true"
        prometheus.io/scheme: http
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: localhost:5001/go-server
          ports:
            - containerPort: 8090
              name: http-go-svc
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
            
