apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:latest
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_USERNAME
          value: sonarqube
        - name: SONARQUBE_JDBC_PASSWORD
          value: sonarqube
        - name: SONARQUBE_JDBC_URL
          value: jdbc:postgresql://postgresql:5432/sonarqube
        # resources:
        #   limits:
        #     cpu: 500m
        #     memory: 500Mi
        #   requests:
        #     cpu: 250m
        #     memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - name: http
      protocol: TCP
      port: 9000
      nodePort: 30900
    - name: db
      protocol: TCP
      port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: sonarqube
        - name: POSTGRES_PASSWORD
          value: sonarqube
        - name: POSTGRES_DB
          value: sonarqube
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 250Mi
