---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-sts-nginx
  labels:
    app: sts-nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: sts-nginx
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20