---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-nginx
  labels:
    app: sts-nginx
spec:
  selector:
    matchLabels:
      app: sts-nginx
  serviceName: service-sts-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: sts-nginx
    spec:
      containers:
      - name: sts-nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "10m"
            memory: "10Mi"
          requests:
            cpu: "5m"
            memory: "5Mi"
        volumeMounts:
        - name: nginx-persistent-storage
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: nginx-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Mi
