apiVersion: v1
kind: Service
metadata:
  name: service-sts-nginx
spec:
  selector:
    app: sts-nginx
  type: NodePort
  ports:
  - name: http-web-svc
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30802