apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: go-server
spec:
  template:
    spec:
      containers:
      - image: haroldo89/go-server:0.0.1
        ports:
        - containerPort: 8090